@echo off
echo Running All VehicleShield Test Suites...
set PYTHONPATH=backend
echo [1/3] Testing Indian Plate Normalizer...
python -m unittest backend/tests/test_normalizer.py
echo [2/3] Testing CV & OCR Pipeline...
python -m unittest backend/tests/test_cv_pipeline.py
echo [3/3] Testing API & Auth Endpoints...
python -m unittest backend/tests/test_api.py
echo All tests completed.
pause
